RSpec.describe 'database'  do
  def run_script(commands)
    raw_output = nil
    IO.popen("./build/db", "r+") do |pipe|
      commands.each do |command|
        pipe.puts command
      end

      pipe.close_write

  #read entire output
      raw_output = pipe.gets(nil)
    end
    raw_output.split("\n")
  end

  it 'prints a hello world' do
    result = run_script([
    ])
    expect(result).to match_array([
      "Yo, Peanut!"
    ])
  end
end
